"""add vip product ops snapshots

Revision ID: 20260522_0002
Revises: 20260521_0001
Create Date: 2026-05-22 00:02:00
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op


revision: str = "20260522_0002"
down_revision: str | None = "20260521_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS vip_product_ops_snapshots (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            snapshot_date DATE NOT NULL,
            source_workbook TEXT NOT NULL DEFAULT '',
            source_sheet TEXT NOT NULL DEFAULT '',
            source_row_number TEXT NOT NULL DEFAULT '',
            raw_payload JSON NOT NULL DEFAULT '{}'::json,
            goods_code TEXT,
            style_code TEXT,
            goods_id TEXT,
            p_spu TEXT,
            category_l3 TEXT,
            goods_status TEXT,
            market_price NUMERIC(10, 2),
            vip_price NUMERIC(10, 2),
            final_price NUMERIC(10, 2),
            sales_tag TEXT,
            goods_tag TEXT,
            extra_fields JSON,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT date_trunc('minute', now()),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT date_trunc('minute', now()),
            CONSTRAINT uq_ops_snapshot_date_goods UNIQUE (snapshot_date, goods_id)
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_ops_snapshots_goods_code_date "
        "ON vip_product_ops_snapshots (goods_code, snapshot_date)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_ops_snapshots_snapshot_date "
        "ON vip_product_ops_snapshots (snapshot_date)"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS vip_product_ops_snapshots")
