"""consolidate fine table snapshot row tables by year

Revision ID: 20260604_0016
Revises: 20260604_0015
Create Date: 2026-06-04 15:50:00
"""
from __future__ import annotations

from collections.abc import Sequence
from datetime import date

import sqlalchemy as sa
from alembic import op


revision: str = "20260604_0016"
down_revision: str | None = "20260604_0015"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _year_table_name(year: int) -> str:
    return f"fine_table_snapshot_rows_{year:04d}"


def _month_table_name(month_start: date) -> str:
    return f"fine_table_snapshot_rows_{month_start.year:04d}_{month_start.month:02d}"


def _create_row_table(table_name: str) -> None:
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {table_name} (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            batch_id BIGINT NOT NULL REFERENCES fine_table_snapshot_batches(id) ON DELETE CASCADE,
            sku TEXT,
            original_sku TEXT,
            row_index INTEGER NOT NULL,
            payload JSON NOT NULL,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT date_trunc('minute', now()),
            CONSTRAINT uq_{table_name}_batch_row_index UNIQUE (batch_id, row_index)
        )
        """
    )
    op.execute(f"CREATE INDEX IF NOT EXISTS idx_{table_name}_batch_sku ON {table_name} (batch_id, sku)")
    op.execute(
        f"CREATE INDEX IF NOT EXISTS idx_{table_name}_batch_original_sku "
        f"ON {table_name} (batch_id, original_sku)"
    )


def upgrade() -> None:
    bind = op.get_bind()
    month_tables = [
        row.tablename
        for row in bind.execute(
            sa.text(
                """
                SELECT tablename
                FROM pg_tables
                WHERE schemaname = current_schema()
                  AND tablename ~ '^fine_table_snapshot_rows_[0-9]{4}_[0-9]{2}$'
                ORDER BY tablename
                """
            )
        )
    ]
    for month_table in month_tables:
        year = int(month_table.removeprefix("fine_table_snapshot_rows_")[:4])
        year_table = _year_table_name(year)
        _create_row_table(year_table)
        bind.execute(
            sa.text(
                f"""
                INSERT INTO {year_table} (batch_id, sku, original_sku, row_index, payload, created_at)
                SELECT batch_id, sku, original_sku, row_index, payload, created_at
                FROM {month_table}
                ON CONFLICT (batch_id, row_index) DO NOTHING
                """
            )
        )
        op.execute(f"DROP TABLE IF EXISTS {month_table}")

    legacy_years = [
        row.snapshot_year
        for row in bind.execute(
            sa.text(
                """
                SELECT DISTINCT extract(year FROM batches.snapshot_date)::int AS snapshot_year
                FROM fine_table_snapshot_rows rows
                JOIN fine_table_snapshot_batches batches ON batches.id = rows.batch_id
                ORDER BY snapshot_year
                """
            )
        )
    ]
    for year in legacy_years:
        year_table = _year_table_name(year)
        _create_row_table(year_table)
        bind.execute(
            sa.text(
                f"""
                INSERT INTO {year_table} (batch_id, sku, original_sku, row_index, payload, created_at)
                SELECT rows.batch_id, rows.sku, rows.original_sku, rows.row_index, rows.payload, rows.created_at
                FROM fine_table_snapshot_rows rows
                JOIN fine_table_snapshot_batches batches ON batches.id = rows.batch_id
                WHERE batches.snapshot_date >= :start_date
                  AND batches.snapshot_date < :next_year
                ON CONFLICT (batch_id, row_index) DO NOTHING
                """
            ),
            {"start_date": date(year, 1, 1), "next_year": date(year + 1, 1, 1)},
        )
    if legacy_years:
        op.execute("TRUNCATE TABLE fine_table_snapshot_rows RESTART IDENTITY")


def downgrade() -> None:
    bind = op.get_bind()
    year_tables = [
        row.tablename
        for row in bind.execute(
            sa.text(
                """
                SELECT tablename
                FROM pg_tables
                WHERE schemaname = current_schema()
                  AND tablename ~ '^fine_table_snapshot_rows_[0-9]{4}$'
                ORDER BY tablename
                """
            )
        )
    ]
    for year_table in year_tables:
        year = int(year_table.removeprefix("fine_table_snapshot_rows_"))
        months = [
            row.month_start
            for row in bind.execute(
                sa.text(
                    f"""
                    SELECT DISTINCT date_trunc('month', batches.snapshot_date)::date AS month_start
                    FROM {year_table} rows
                    JOIN fine_table_snapshot_batches batches ON batches.id = rows.batch_id
                    ORDER BY month_start
                    """
                )
            )
        ]
        for month_start in months:
            next_month = date(month_start.year + (1 if month_start.month == 12 else 0), 1 if month_start.month == 12 else month_start.month + 1, 1)
            month_table = _month_table_name(month_start)
            _create_row_table(month_table)
            bind.execute(
                sa.text(
                    f"""
                    INSERT INTO {month_table} (batch_id, sku, original_sku, row_index, payload, created_at)
                    SELECT rows.batch_id, rows.sku, rows.original_sku, rows.row_index, rows.payload, rows.created_at
                    FROM {year_table} rows
                    JOIN fine_table_snapshot_batches batches ON batches.id = rows.batch_id
                    WHERE batches.snapshot_date >= :month_start
                      AND batches.snapshot_date < :next_month
                    ON CONFLICT (batch_id, row_index) DO NOTHING
                    """
                ),
                {"month_start": month_start, "next_month": next_month},
            )
        op.execute(f"DROP TABLE IF EXISTS {year_table}")
