"""Add the unified Dewu order detail table.

Revision ID: 20260819_0055
Revises: 20260817_0054
Create Date: 2026-08-19
"""

from __future__ import annotations

from alembic import op


revision = "20260819_0055"
down_revision = "20260817_0054"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS dewu_orders (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            brand_group TEXT NOT NULL,
            brand_label TEXT NOT NULL,
            source_workbook TEXT NOT NULL,
            source_sheet TEXT NOT NULL,
            source_row_number INTEGER NOT NULL,
            source_modified_at TIMESTAMP WITH TIME ZONE,
            order_date DATE,
            order_number TEXT NOT NULL,
            order_type TEXT,
            spu_id TEXT,
            sku_id TEXT,
            product_name TEXT,
            goods_code TEXT,
            sku_goods_code TEXT,
            brand_name TEXT,
            specification TEXT,
            quantity INTEGER,
            bid_amount NUMERIC(18, 2),
            seller_discount_amount NUMERIC(18, 2),
            consumer_postage_subsidy_amount NUMERIC(18, 2),
            estimated_income_amount NUMERIC(18, 2),
            remaining_shipping_time TEXT,
            close_reason TEXT,
            delivery_party TEXT,
            logistics_company TEXT,
            logistics_tracking_number TEXT,
            appointment_number TEXT,
            order_status TEXT,
            order_source TEXT,
            dewu_receiving_address TEXT,
            recipient_name TEXT,
            recipient_phone TEXT,
            recipient_province TEXT,
            recipient_city TEXT,
            recipient_district TEXT,
            recipient_street TEXT,
            recipient_detail_address TEXT,
            service_guarantee TEXT,
            direct_shipping_pickup_time TEXT,
            direct_shipping_warehouse TEXT,
            user_identifier TEXT,
            order_remark TEXT,
            order_tag TEXT,
            buyer_order_time TEXT,
            buyer_payment_time TEXT,
            promised_delivery_time TEXT,
            seller_shipping_time TEXT,
            platform_receiving_time TEXT,
            platform_shipping_time TEXT,
            order_closed_time TEXT,
            intent_deposit_amount NUMERIC(18, 2),
            full_payment_amount NUMERIC(18, 2),
            sub_waybill_number TEXT,
            third_party_order_number TEXT,
            onsite_ticket_address TEXT,
            has_engraving_remark TEXT,
            buyer_remark TEXT,
            custom_product_detail TEXT,
            preorder_number TEXT,
            appointment_store TEXT,
            verification_store TEXT,
            verification_time TEXT,
            order_identifier TEXT,
            pickup_carrier TEXT,
            pickup_waybill_number TEXT,
            pickup_code TEXT,
            sn_code TEXT,
            imei1 TEXT,
            imei2 TEXT,
            reservation_open_time TEXT,
            extra_fields JSONB,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT date_trunc('minute', now()),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT date_trunc('minute', now())
        )
        """
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_dewu_orders_brand_order_date ON dewu_orders (brand_group, order_date)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_dewu_orders_order_number ON dewu_orders (order_number)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_dewu_orders_goods_code ON dewu_orders (goods_code text_pattern_ops)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_dewu_orders_sku_id ON dewu_orders (sku_id)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_dewu_orders_order_status ON dewu_orders (order_status)")


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS dewu_orders")
