"""move supplier factory codes to standalone table

Revision ID: 20260604_0013
Revises: 20260604_0012
Create Date: 2026-06-04 14:12:00
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op


revision: str = "20260604_0013"
down_revision: str | None = "20260604_0012"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS supplier_factory_codes (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            factory_code TEXT NOT NULL,
            supplier_name TEXT NOT NULL,
            source_file TEXT NOT NULL DEFAULT '',
            created_at TIMESTAMPTZ DEFAULT date_trunc('minute', now()),
            updated_at TIMESTAMPTZ DEFAULT date_trunc('minute', now()),
            CONSTRAINT uq_supplier_factory_codes_factory_code UNIQUE (factory_code)
        )
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_supplier_factory_codes_supplier_name
        ON supplier_factory_codes (supplier_name)
        """
    )
    op.execute(
        """
        INSERT INTO supplier_factory_codes (factory_code, supplier_name, source_file)
        SELECT DISTINCT ON (factory_code)
            factory_code,
            name,
            '往来单位信息数据-2026_06_04-13_55_08'
        FROM suppliers
        WHERE coalesce(factory_code, '') <> ''
          AND coalesce(name, '') <> ''
        ORDER BY factory_code, id DESC
        ON CONFLICT (factory_code) DO UPDATE
        SET supplier_name = EXCLUDED.supplier_name,
            source_file = EXCLUDED.source_file,
            updated_at = date_trunc('minute', now())
        """
    )
    op.execute("DELETE FROM suppliers WHERE coalesce(factory_code, '') <> ''")
    op.execute("DROP INDEX IF EXISTS idx_suppliers_factory_code")
    op.execute("ALTER TABLE suppliers DROP COLUMN IF EXISTS factory_code")


def downgrade() -> None:
    op.execute("ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS factory_code TEXT")
    op.execute("CREATE INDEX IF NOT EXISTS idx_suppliers_factory_code ON suppliers (factory_code)")
    op.execute(
        """
        INSERT INTO suppliers (name, factory_code)
        SELECT supplier_name, factory_code
        FROM supplier_factory_codes
        ON CONFLICT (name) DO UPDATE
        SET factory_code = EXCLUDED.factory_code,
            updated_at = date_trunc('minute', now())
        """
    )
    op.execute("DROP TABLE IF EXISTS supplier_factory_codes")
