"""store fine table snapshot rows by year

Revision ID: 20260604_0015
Revises: 20260604_0014
Create Date: 2026-06-04 15:35:00
"""
from __future__ import annotations

from collections.abc import Sequence
from datetime import date

import sqlalchemy as sa
from alembic import op


revision: str = "20260604_0015"
down_revision: str | None = "20260604_0014"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _table_name(year: int) -> str:
    return f"fine_table_snapshot_rows_{year:04d}"


def _create_year_table(table_name: str) -> None:
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {table_name} (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            batch_id BIGINT NOT NULL REFERENCES fine_table_snapshot_batches(id) ON DELETE CASCADE,
            sku TEXT,
            original_sku TEXT,
            row_index INTEGER NOT NULL,
            payload JSON NOT NULL,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT date_trunc('minute', now()),
            CONSTRAINT uq_{table_name}_batch_row_index UNIQUE (batch_id, row_index)
        )
        """
    )
    op.execute(
        f"CREATE INDEX IF NOT EXISTS idx_{table_name}_batch_sku "
        f"ON {table_name} (batch_id, sku)"
    )
    op.execute(
        f"CREATE INDEX IF NOT EXISTS idx_{table_name}_batch_original_sku "
        f"ON {table_name} (batch_id, original_sku)"
    )


def upgrade() -> None:
    bind = op.get_bind()
    years = [
        row.snapshot_year
        for row in bind.execute(
            sa.text(
                """
                SELECT DISTINCT extract(year FROM batches.snapshot_date)::int AS snapshot_year
                FROM fine_table_snapshot_rows rows
                JOIN fine_table_snapshot_batches batches ON batches.id = rows.batch_id
                ORDER BY snapshot_year
                """
            )
        )
    ]
    for year in years:
        start_date = date(year, 1, 1)
        next_year = date(year + 1, 1, 1)
        table_name = _table_name(year)
        _create_year_table(table_name)
        bind.execute(
            sa.text(
                f"""
                INSERT INTO {table_name} (batch_id, sku, original_sku, row_index, payload, created_at)
                SELECT rows.batch_id, rows.sku, rows.original_sku, rows.row_index, rows.payload, rows.created_at
                FROM fine_table_snapshot_rows rows
                JOIN fine_table_snapshot_batches batches ON batches.id = rows.batch_id
                WHERE batches.snapshot_date >= :start_date
                  AND batches.snapshot_date < :next_year
                ON CONFLICT (batch_id, row_index) DO NOTHING
                """
            ),
            {"start_date": start_date, "next_year": next_year},
        )

    if years:
        op.execute("TRUNCATE TABLE fine_table_snapshot_rows RESTART IDENTITY")


def downgrade() -> None:
    bind = op.get_bind()
    table_names = [
        row.tablename
        for row in bind.execute(
            sa.text(
                """
                SELECT tablename
                FROM pg_tables
                WHERE schemaname = current_schema()
                  AND tablename ~ '^fine_table_snapshot_rows_[0-9]{4}$'
                ORDER BY tablename
                """
            )
        )
    ]
    for table_name in table_names:
        bind.execute(
            sa.text(
                f"""
                INSERT INTO fine_table_snapshot_rows (batch_id, sku, original_sku, row_index, payload, created_at)
                SELECT batch_id, sku, original_sku, row_index, payload, created_at
                FROM {table_name}
                ON CONFLICT (batch_id, row_index) DO NOTHING
                """
            )
        )
        op.execute(f"DROP TABLE IF EXISTS {table_name}")
