"""add daily task statuses and price source dates

Revision ID: 20260608_0019
Revises: 20260605_0018
Create Date: 2026-06-08 14:10:00
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op


revision: str = "20260608_0019"
down_revision: str | None = "20260605_0018"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS scheduled_task_statuses (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            task_name TEXT NOT NULL,
            business_date DATE NOT NULL,
            status TEXT NOT NULL,
            source_path TEXT,
            message TEXT,
            result JSON,
            attempts INTEGER NOT NULL DEFAULT 0,
            first_started_at TIMESTAMP WITH TIME ZONE,
            last_started_at TIMESTAMP WITH TIME ZONE,
            finished_at TIMESTAMP WITH TIME ZONE,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT date_trunc('minute', now()),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT date_trunc('minute', now()),
            CONSTRAINT uq_scheduled_task_statuses_task_date UNIQUE (task_name, business_date)
        )
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_scheduled_task_statuses_task_status_date
        ON scheduled_task_statuses (task_name, status, business_date)
        """
    )
    op.execute("ALTER TABLE jst_product_price ADD COLUMN IF NOT EXISTS source_date TEXT")
    op.execute("ALTER TABLE jst_product_price ADD COLUMN IF NOT EXISTS source_date_value DATE")
    op.execute(
        """
        UPDATE jst_product_price
        SET
            source_date = COALESCE(source_date, to_char(current_date, 'YYYY-MM-DD')),
            source_date_value = COALESCE(source_date_value, current_date)
        WHERE source_date IS NULL
           OR source_date = ''
           OR source_date_value IS NULL
        """
    )
    op.execute("ALTER TABLE jst_product_price ALTER COLUMN source_date SET NOT NULL")
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conname = 'uq_jst_price_code_name'
            ) THEN
                ALTER TABLE jst_product_price DROP CONSTRAINT uq_jst_price_code_name;
            END IF;
        END $$;
        """
    )
    op.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uq_jst_price_date_code_name
        ON jst_product_price (source_date, goods_code, goods_full_name)
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_jst_price_source_date_value
        ON jst_product_price (source_date_value)
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS scheduled_task_statuses")
    op.execute("DROP INDEX IF EXISTS idx_jst_price_source_date_value")
    op.execute("DROP INDEX IF EXISTS uq_jst_price_date_code_name")
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conname = 'uq_jst_price_code_name'
            ) THEN
                ALTER TABLE jst_product_price
                ADD CONSTRAINT uq_jst_price_code_name UNIQUE (goods_code, goods_full_name);
            END IF;
        END $$;
        """
    )
    op.execute("ALTER TABLE jst_product_price DROP COLUMN IF EXISTS source_date_value")
    op.execute("ALTER TABLE jst_product_price DROP COLUMN IF EXISTS source_date")
