"""add jst product profiles

Revision ID: 20260628_0037
Revises: 20260624_0036
Create Date: 2026-06-28
"""

from __future__ import annotations

from alembic import op


revision = "20260628_0037"
down_revision = "20260624_0036"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS jst_product_profiles (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_workbook TEXT NOT NULL DEFAULT '',
            source_sheet TEXT NOT NULL DEFAULT '',
            source_row_number TEXT NOT NULL DEFAULT '',
            raw_payload JSON NOT NULL DEFAULT '{}'::json,
            product_code TEXT,
            style_code TEXT,
            color_name TEXT,
            size_barcode TEXT,
            extra_fields JSON,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT date_trunc('minute', now()),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT date_trunc('minute', now()),
            CONSTRAINT uq_jst_product_profiles_product_code UNIQUE (product_code)
        )
        """
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_jst_product_profiles_style_code ON jst_product_profiles (style_code)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_jst_product_profiles_color_name ON jst_product_profiles (color_name)")


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS jst_product_profiles")
