"""Add the optimized factory-channel daily sales summary.

Revision ID: 20260821_0057
Revises: 20260820_0056
Create Date: 2026-08-21
"""

from __future__ import annotations

from alembic import op


revision = "20260821_0057"
down_revision = "20260820_0056"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS factory_channel_sales_daily_summaries (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            brand TEXT NOT NULL,
            sales_date DATE NOT NULL,
            product_code TEXT NOT NULL DEFAULT '',
            channel_group TEXT NOT NULL DEFAULT '',
            match_status TEXT NOT NULL DEFAULT 'matched',
            quantity BIGINT NOT NULL DEFAULT 0,
            created_at TIMESTAMPTZ DEFAULT date_trunc('minute', now()),
            updated_at TIMESTAMPTZ DEFAULT date_trunc('minute', now()),
            CONSTRAINT uq_factory_channel_sales_daily_summary_key
                UNIQUE (brand, sales_date, product_code, channel_group, match_status)
        )
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_factory_channel_sales_daily_summary_brand_date
        ON factory_channel_sales_daily_summaries (brand, sales_date)
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS factory_channel_sales_daily_summaries")

