"""Store product auxiliary attribute options for product archive forms."""

from alembic import op


revision = "20260827_0060"
down_revision = ("20260821_0059", "20260823_0031")
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS product_auxiliary_attributes (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            brand_scope TEXT NOT NULL,
            attribute_type TEXT NOT NULL,
            attribute_name TEXT NOT NULL,
            source_workbook TEXT NOT NULL DEFAULT '',
            source_sheet TEXT NOT NULL DEFAULT '',
            source_row_number TEXT NOT NULL DEFAULT '',
            created_at TIMESTAMPTZ DEFAULT date_trunc('minute', now()),
            updated_at TIMESTAMPTZ DEFAULT date_trunc('minute', now()),
            CONSTRAINT uq_product_auxiliary_attributes_scope_type_name
                UNIQUE (brand_scope, attribute_type, attribute_name)
        );
        CREATE INDEX IF NOT EXISTS idx_product_auxiliary_attributes_scope_type
            ON product_auxiliary_attributes (brand_scope, attribute_type);
        CREATE INDEX IF NOT EXISTS idx_product_auxiliary_attributes_name
            ON product_auxiliary_attributes (attribute_name);
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS product_auxiliary_attributes")
