"""add gj merged product info table

Revision ID: 20260527_0008
Revises: 20260527_0007
Create Date: 2026-05-27 00:08:00
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op


revision: str = "20260527_0008"
down_revision: str | None = "20260527_0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS gj_merged_product_info (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_date TEXT NOT NULL,
            source_date_value DATE,
            source_workbook TEXT NOT NULL DEFAULT '',
            source_sheet TEXT NOT NULL DEFAULT '',
            source_row_number TEXT NOT NULL DEFAULT '',
            raw_payload JSON NOT NULL DEFAULT '{}'::json,
            row_no INTEGER,
            goods_code TEXT,
            original_goods_code TEXT,
            goods_full_name TEXT,
            barcode TEXT,
            factory_code TEXT,
            product_name TEXT,
            execution_standard TEXT,
            barcode_format TEXT,
            launch_date TEXT,
            insole_material TEXT,
            outsole_material TEXT,
            lining_material TEXT,
            upper_material TEXT,
            shoe_box_spec TEXT,
            brand TEXT,
            disabled_flag TEXT,
            primary_supplier TEXT,
            extra_fields JSON,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT date_trunc('minute', now()),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT date_trunc('minute', now()),
            CONSTRAINT uq_gj_merged_product_info_date_code UNIQUE (source_date, goods_code)
        )
        """
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_gj_merged_product_info_goods_code ON gj_merged_product_info (goods_code)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_gj_merged_product_info_original_code ON gj_merged_product_info (original_goods_code)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_gj_merged_product_info_source_date ON gj_merged_product_info (source_date_value)")


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS gj_merged_product_info")
