"""Add deduplicated fine-table snapshot payload stores."""

from alembic import op


revision = "20260731_0049"
down_revision = "20260729_0048"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS fine_table_snapshot_payloads (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            brand TEXT NOT NULL,
            content_hash TEXT NOT NULL,
            payload JSONB NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT date_trunc('minute', now()),
            CONSTRAINT uq_fine_table_snapshot_payloads_brand_hash UNIQUE (brand, content_hash)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS fine_table_snapshot_metrics (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            brand TEXT NOT NULL,
            content_hash TEXT NOT NULL,
            payload JSONB NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT date_trunc('minute', now()),
            CONSTRAINT uq_fine_table_snapshot_metrics_brand_hash UNIQUE (brand, content_hash)
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_fine_table_snapshot_payloads_hash "
        "ON fine_table_snapshot_payloads (brand, content_hash)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_fine_table_snapshot_metrics_hash "
        "ON fine_table_snapshot_metrics (brand, content_hash)"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS fine_table_snapshot_metrics")
    op.execute("DROP TABLE IF EXISTS fine_table_snapshot_payloads")
