"""store full JST inventory detail

Revision ID: 20260721_0042
Revises: 20260720_0041
Create Date: 2026-07-21
"""

from __future__ import annotations

from alembic import op


revision = "20260721_0042"
down_revision = "20260720_0041"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS jst_full_stock (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            sync_date DATE NOT NULL,
            source_workbook TEXT NOT NULL,
            source_sheet TEXT NOT NULL,
            source_row_number TEXT NOT NULL,
            image_url TEXT,
            style_code TEXT,
            product_code TEXT NOT NULL,
            product_name TEXT,
            color_spec TEXT,
            color TEXT,
            size TEXT,
            product_tag TEXT,
            actual_stock_qty INTEGER,
            order_occupy_qty INTEGER,
            available_qty INTEGER,
            stock_sale_days NUMERIC(12, 2),
            purchase_feature TEXT,
            suggested_purchase_qty INTEGER,
            purchase_in_transit_qty INTEGER,
            safety_stock_min_qty INTEGER,
            safety_stock_max_qty INTEGER,
            safety_stock_delivery_days_min INTEGER,
            safety_stock_days_max INTEGER,
            warehouse_pending_qty INTEGER,
            return_warehouse_stock_qty INTEGER,
            purchase_warehouse_stock_qty INTEGER,
            exception_warehouse_qty INTEGER,
            off_shelf_warehouse_qty INTEGER,
            worn_warehouse_qty INTEGER,
            live_warehouse_qty INTEGER,
            off_shelf_inventory_qty INTEGER,
            processing_warehouse_qty INTEGER,
            temporary_location_qty INTEGER,
            transfer_in_transit_qty INTEGER,
            return_in_transit_qty INTEGER,
            inventory_sync_status TEXT,
            main_warehouse_location TEXT,
            yesterday_sales_qty INTEGER,
            sales_7d_qty INTEGER,
            sales_15d_qty INTEGER,
            yesterday_return_qty INTEGER,
            return_7d_qty INTEGER,
            return_15d_qty INTEGER,
            inventory_updated_at TEXT,
            warehouse_name TEXT,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT date_trunc('minute', now()),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT date_trunc('minute', now())
        )
        """
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_jst_full_stock_product_code ON jst_full_stock (product_code)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_jst_full_stock_product_size ON jst_full_stock (product_code, size)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_jst_full_stock_style_code ON jst_full_stock (style_code)")


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS jst_full_stock")
