"""drop legacy fine table snapshot rows table

Revision ID: 20260605_0018
Revises: 20260605_0017
Create Date: 2026-06-05 10:30:00
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op


revision: str = "20260605_0018"
down_revision: str | None = "20260605_0017"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("DROP TABLE IF EXISTS fine_table_snapshot_rows")


def downgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS fine_table_snapshot_rows (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            batch_id BIGINT NOT NULL REFERENCES fine_table_snapshot_batches(id) ON DELETE CASCADE,
            sku TEXT,
            original_sku TEXT,
            row_index INTEGER NOT NULL,
            payload JSON NOT NULL,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT date_trunc('minute', now()),
            CONSTRAINT uq_fine_table_snapshot_rows_batch_row_index UNIQUE (batch_id, row_index)
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_fine_table_snapshot_rows_batch_sku "
        "ON fine_table_snapshot_rows (batch_id, sku)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_fine_table_snapshot_rows_batch_original_sku "
        "ON fine_table_snapshot_rows (batch_id, original_sku)"
    )
