"""add vip daily compass snapshots

Revision ID: 20260527_0007
Revises: 20260526_0006
Create Date: 2026-05-27 00:07:00
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op


revision: str = "20260527_0007"
down_revision: str | None = "20260526_0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS vip_product_daily_snapshots (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            snapshot_date DATE NOT NULL,
            source_workbook TEXT NOT NULL DEFAULT '',
            source_sheet TEXT NOT NULL DEFAULT '',
            source_row_number TEXT NOT NULL DEFAULT '',
            raw_payload JSON NOT NULL DEFAULT '{}'::json,
            goods_id TEXT,
            date TEXT,
            goods_name TEXT,
            goods_code TEXT,
            style_code TEXT,
            p_spu_id TEXT,
            goods_image TEXT,
            brand_sn TEXT,
            brand_name TEXT,
            category_l3 TEXT,
            first_listing_time TEXT,
            main_style TEXT,
            detail_uv INTEGER,
            ctr TEXT,
            fav_count INTEGER,
            sales_amount NUMERIC(10, 2),
            sales_volume INTEGER,
            customer_count INTEGER,
            purchase_conversion TEXT,
            reject_count INTEGER,
            reject_rate TEXT,
            report_type TEXT,
            period TEXT,
            date_range TEXT,
            report_start_date DATE,
            report_end_date DATE,
            extra_fields JSON,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT date_trunc('minute', now()),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT date_trunc('minute', now()),
            CONSTRAINT uq_daily_snapshot_date_goods UNIQUE (snapshot_date, goods_id)
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_daily_snapshots_goods_code_date "
        "ON vip_product_daily_snapshots (goods_code, snapshot_date)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_daily_snapshots_snapshot_date "
        "ON vip_product_daily_snapshots (snapshot_date)"
    )
    op.execute(
        """
        INSERT INTO vip_product_daily_snapshots (
            snapshot_date,
            source_workbook,
            source_sheet,
            source_row_number,
            raw_payload,
            goods_id,
            date,
            goods_name,
            goods_code,
            style_code,
            p_spu_id,
            goods_image,
            brand_sn,
            brand_name,
            category_l3,
            first_listing_time,
            main_style,
            detail_uv,
            ctr,
            fav_count,
            sales_amount,
            sales_volume,
            customer_count,
            purchase_conversion,
            reject_count,
            reject_rate,
            report_type,
            period,
            date_range,
            report_start_date,
            report_end_date,
            extra_fields
        )
        SELECT
            COALESCE(report_end_date, CURRENT_DATE),
            source_workbook,
            source_sheet,
            source_row_number,
            raw_payload,
            goods_id,
            date,
            goods_name,
            goods_code,
            style_code,
            p_spu_id,
            goods_image,
            brand_sn,
            brand_name,
            category_l3,
            first_listing_time,
            main_style,
            detail_uv,
            ctr,
            fav_count,
            sales_amount,
            sales_volume,
            customer_count,
            purchase_conversion,
            reject_count,
            reject_rate,
            report_type,
            period,
            date_range,
            report_start_date,
            report_end_date,
            extra_fields
        FROM vip_product_daily
        WHERE report_type = '罗盘'
          AND period = '1d'
          AND goods_id IS NOT NULL
        ON CONFLICT (snapshot_date, goods_id) DO NOTHING
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS vip_product_daily_snapshots")
