"""Create annual product-goods historical order tables.

Revision ID: 20260722_0045
Revises: 20260721_0044
Create Date: 2026-07-22
"""

from __future__ import annotations

from alembic import op


revision = "20260722_0045"
down_revision = "20260721_0044"
branch_labels = None
depends_on = None


def upgrade() -> None:
    for year in range(2022, 2027):
        table = f"product_goods_historical_orders_{year}"
        op.execute(
            f"""
            CREATE TABLE IF NOT EXISTS {table} (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                brand TEXT NOT NULL,
                order_date DATE NOT NULL,
                original_sku TEXT NOT NULL,
                channel TEXT,
                order_quantity INTEGER NOT NULL,
                source_workbook TEXT NOT NULL,
                source_sheet TEXT NOT NULL,
                source_row_number INTEGER NOT NULL,
                created_at TIMESTAMP WITH TIME ZONE DEFAULT date_trunc('minute', now()),
                updated_at TIMESTAMP WITH TIME ZONE DEFAULT date_trunc('minute', now()),
                CONSTRAINT uq_{table}_source_row UNIQUE (source_workbook, source_sheet, source_row_number)
            )
            """
        )
        op.execute(f"CREATE INDEX IF NOT EXISTS idx_{table}_brand_original ON {table} (brand, original_sku)")
        op.execute(f"CREATE INDEX IF NOT EXISTS idx_{table}_order_date ON {table} (order_date)")


def downgrade() -> None:
    for year in range(2022, 2027):
        op.execute(f"DROP TABLE IF EXISTS product_goods_historical_orders_{year}")
