"""add fine table snapshots

Revision ID: 20260603_0010
Revises: 20260527_0009
Create Date: 2026-06-03 00:10:00
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op


revision: str = "20260603_0010"
down_revision: str | None = "20260527_0009"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS fine_table_snapshot_batches (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            brand TEXT NOT NULL,
            snapshot_date DATE NOT NULL,
            total_rows INTEGER NOT NULL DEFAULT 0,
            latest_order_date TEXT,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT date_trunc('minute', now()),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT date_trunc('minute', now()),
            CONSTRAINT uq_fine_table_snapshot_batches_brand_date UNIQUE (brand, snapshot_date)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS fine_table_snapshot_rows (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            batch_id BIGINT NOT NULL REFERENCES fine_table_snapshot_batches(id) ON DELETE CASCADE,
            brand TEXT NOT NULL,
            sku TEXT,
            original_sku TEXT,
            row_index INTEGER NOT NULL,
            payload JSON NOT NULL,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT date_trunc('minute', now())
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_fine_table_snapshot_batches_brand_date "
        "ON fine_table_snapshot_batches (brand, snapshot_date)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_fine_table_snapshot_rows_batch "
        "ON fine_table_snapshot_rows (batch_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_fine_table_snapshot_rows_batch_sku "
        "ON fine_table_snapshot_rows (batch_id, sku)"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS fine_table_snapshot_rows")
    op.execute("DROP TABLE IF EXISTS fine_table_snapshot_batches")
