"""Add configurable product size groups and barcode details."""

from alembic import op


revision = "20260803_0050"
down_revision = "20260731_0049"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS size_groups (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL,
            created_at TIMESTAMPTZ DEFAULT date_trunc('minute', now()),
            updated_at TIMESTAMPTZ DEFAULT date_trunc('minute', now()),
            CONSTRAINT uq_size_groups_name UNIQUE (name)
        );
        CREATE TABLE IF NOT EXISTS size_group_items (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            size_group_id BIGINT NOT NULL REFERENCES size_groups(id) ON DELETE CASCADE,
            size_name TEXT NOT NULL,
            barcode TEXT NOT NULL,
            sort_order INTEGER NOT NULL DEFAULT 0,
            created_at TIMESTAMPTZ DEFAULT date_trunc('minute', now()),
            updated_at TIMESTAMPTZ DEFAULT date_trunc('minute', now()),
            CONSTRAINT uq_size_group_items_group_size UNIQUE (size_group_id, size_name),
            CONSTRAINT uq_size_group_items_group_barcode UNIQUE (size_group_id, barcode)
        );
        CREATE INDEX IF NOT EXISTS idx_size_group_items_group_sort
            ON size_group_items (size_group_id, sort_order);
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS size_group_items")
    op.execute("DROP TABLE IF EXISTS size_groups")
