"""store product-goods shop to channel mappings

Revision ID: 20260721_0043
Revises: 20260721_0042
Create Date: 2026-07-21
"""

from __future__ import annotations

from alembic import op


revision = "20260721_0043"
down_revision = "20260721_0042"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS product_goods_shop_channel_mappings (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            brand TEXT NOT NULL,
            shop_name TEXT NOT NULL,
            channel TEXT NOT NULL,
            source_workbook TEXT NOT NULL,
            source_sheet TEXT NOT NULL,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT date_trunc('minute', now()),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT date_trunc('minute', now()),
            CONSTRAINT uq_product_goods_shop_channel_brand_shop UNIQUE (brand, shop_name)
        )
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_product_goods_shop_channel_brand
        ON product_goods_shop_channel_mappings (brand)
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS product_goods_shop_channel_mappings")
