"""Add user-specific purchase print templates.

Revision ID: 20260915_0068
Revises: 20260915_0067
Create Date: 2026-09-15
"""

from __future__ import annotations

from alembic import op


revision = "20260915_0068"
down_revision = "20260915_0067"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS purchase_print_templates (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id BIGINT NOT NULL,
            template_key TEXT NOT NULL DEFAULT 'shoe_box_label',
            config JSON NOT NULL,
            created_at TIMESTAMPTZ DEFAULT date_trunc('minute', now()),
            updated_at TIMESTAMPTZ DEFAULT date_trunc('minute', now()),
            CONSTRAINT uq_purchase_print_templates_user_key UNIQUE (user_id, template_key)
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_purchase_print_templates_user "
        "ON purchase_print_templates (user_id)"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS purchase_print_templates")
