"""add jst stock summary

Revision ID: 20260525_0003
Revises: 20260522_0002
Create Date: 2026-05-25 00:03:00
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op


revision: str = "20260525_0003"
down_revision: str | None = "20260522_0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS jst_stock_summary (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            stock_date TEXT NOT NULL,
            stock_date_value DATE,
            source_workbook TEXT NOT NULL DEFAULT '',
            source_sheet TEXT NOT NULL DEFAULT '',
            source_row_number TEXT NOT NULL DEFAULT '',
            raw_payload JSON NOT NULL DEFAULT '{}'::json,
            product_code TEXT,
            defect_stock_qty INTEGER,
            purchase_in_transit_qty INTEGER,
            off_shelf_qty INTEGER,
            order_occupy_qty INTEGER,
            extra_fields JSON,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT date_trunc('minute', now()),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT date_trunc('minute', now()),
            CONSTRAINT uq_jst_stock_summary_date_code UNIQUE (stock_date, product_code)
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_jst_stock_summary_date_code "
        "ON jst_stock_summary (stock_date, product_code)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_jst_stock_summary_date_value_code "
        "ON jst_stock_summary (stock_date_value, product_code)"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS jst_stock_summary")
