"""add scheduled task execution history

Revision ID: 20260823_0031
Revises: 20260617_0030
Create Date: 2026-08-23 10:00:00
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op


revision: str = "20260823_0031"
down_revision: str | None = "20260617_0030"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS scheduled_task_runs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            task_name TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'running',
            started_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
            finished_at TIMESTAMP WITH TIME ZONE,
            duration_ms BIGINT,
            exit_code INTEGER,
            host_name TEXT,
            process_id INTEGER,
            command TEXT,
            log_path TEXT,
            error_summary TEXT,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
            CONSTRAINT ck_scheduled_task_runs_status
                CHECK (status IN ('running', 'success', 'failed')),
            CONSTRAINT ck_scheduled_task_runs_duration_ms
                CHECK (duration_ms IS NULL OR duration_ms >= 0)
        )
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_scheduled_task_runs_task_started
        ON scheduled_task_runs (task_name, started_at DESC)
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_scheduled_task_runs_status_started
        ON scheduled_task_runs (status, started_at DESC)
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS scheduled_task_runs")
