"""add jst aftersale returns

Revision ID: 20260707_0038
Revises: 20260628_0037
Create Date: 2026-07-07
"""

from __future__ import annotations

from alembic import op


revision = "20260707_0038"
down_revision = "20260628_0037"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS jst_aftersale_returns (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_workbook TEXT NOT NULL DEFAULT '',
            source_sheet TEXT NOT NULL DEFAULT '',
            source_row_number TEXT NOT NULL DEFAULT '',
            raw_payload JSON NOT NULL DEFAULT '{}'::json,
            original_goods_code TEXT,
            returned_qty INTEGER,
            order_date TEXT,
            order_time TEXT,
            platform_site TEXT,
            shop_name TEXT,
            online_order_id TEXT,
            order_date_value DATE,
            order_time_value DATE,
            extra_fields JSON,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT date_trunc('minute', now()),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT date_trunc('minute', now())
        )
        """
    )
    op.execute("ALTER TABLE jst_aftersale_returns ADD COLUMN IF NOT EXISTS order_time TEXT")
    op.execute("ALTER TABLE jst_aftersale_returns ADD COLUMN IF NOT EXISTS platform_site TEXT")
    op.execute("ALTER TABLE jst_aftersale_returns ADD COLUMN IF NOT EXISTS shop_name TEXT")
    op.execute("ALTER TABLE jst_aftersale_returns ADD COLUMN IF NOT EXISTS online_order_id TEXT")
    op.execute("ALTER TABLE jst_aftersale_returns ADD COLUMN IF NOT EXISTS order_time_value DATE")
    op.execute("CREATE INDEX IF NOT EXISTS idx_jst_aftersale_returns_original_code ON jst_aftersale_returns (original_goods_code)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_jst_aftersale_returns_order_date ON jst_aftersale_returns (order_date_value)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_jst_aftersale_returns_order_time ON jst_aftersale_returns (order_time_value)")


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS jst_aftersale_returns")
