from __future__ import annotations


PRODUCT_ARCHIVE_TABLES = {
    "cbanner_mens_products": "千百度男鞋商品档案",
    "cbanner_womens_products": "千百度女鞋商品档案",
    "yandou_products": "烟斗商品档案",
    "eblan_products": "伊伴商品档案",
    "smiley_products": "笑脸商品档案",
    "ni_products": "NI 商品档案",
}


TABLE_DESCRIPTIONS = {
    **{
        table_name: f"{label}；一行代表一个商品货号档案，查询时过滤 deleted_at IS NULL"
        for table_name, label in PRODUCT_ARCHIVE_TABLES.items()
    },
    "color_barcodes": "颜色名称与颜色代码对照表",
    "gj_merged_product_info": "管家婆男女鞋合并商品资料；同一货号可能有多个来源日期，应优先取最新 source_date_value",
    "product_code_mappings": "不同来源商品编码到标准货号的有效映射",
    "v_product_code_mappings": "仅保留有效记录的商品编码标准化视图",
    "product_size_group_mappings": "商品货号到尺码组名称的映射",
    "size_groups": "自定义尺码组主表",
    "size_group_items": "尺码组内的尺码、条码及展示顺序",
    "v_jst_daily_sales": "聚水潭统一逐日销售视图；一行是某日、渠道、商品编码的一条销售事实",
    "v_vip_daily_sales": "唯品统一逐日销售视图；一行是某日、商品编码和尺码的一条销售事实",
    "v_product_goods_historical_sales": "历史工作簿统一销量视图，主要覆盖 2024、2025 等已导入历史年度",
    "product_goods_sales_periods": "货品表年度或月度等期间销量预计算结果，不能与逐日销量重复相加",
    "product_goods_shop_channel_mappings": "品牌下店铺名称到业务平台或赛道的映射",
    "v_product_goods_historical_orders": "历史工作簿统一订单量视图；订单量与销量不是同一指标",
    "jst_full_stock": "聚水潭当前全量库存；按 sync_date、商品编码和尺码保存库存组成",
    "jst_size_stock": "当前商品编码和尺码的在仓库存汇总",
    "jst_stock_summary": "当前商品库存补充汇总，主要提供采购在途、占用和次品库存",
    "jst_size_stock_snapshots": "按日期固化的尺码库存快照",
    "jst_stock_summary_snapshots": "按日期固化的库存补充汇总快照",
    "v_jst_daily_stock_normalized": "聚水潭历史逐日可用库存标准化视图",
    "v_product_goods_detail_snapshots": "货品表历史完整状态快照；明细指标保存在 data JSON 中",
    "v_fine_table_snapshot_rows": "精细表历史行统一视图；展示指标保存在 payload JSON 中",
    "v_vip_product_daily_normalized": "唯品罗盘和商品运营周期指标标准化视图",
    "product_goods_overrides": "货品表人工维护字段，包括平台、四级分类、商品角色、清仓和补单扩展字段",
    "inventory_records": "经营历程和采购单共用的单据头；一行代表一张单据",
    "inventory_details": "经营历程和采购单的商品明细；通过 document_id 关联单据头",
    "v_inventory_records_normalized": "经营历程单据头标准化视图，business_date 为规范业务日期",
    "ai_purchase_records": "采购权限专用虚拟单据头，仅包含 document_type='进货订单' 的有效单据",
    "ai_purchase_details": "采购权限专用虚拟单据明细，仅包含有效进货订单的明细",
    "suppliers": "供应商档案",
    "supplier_brands": "品牌管理及品牌商品档案配置",
    "warehouses": "仓库档案",
    "warehouse_brands": "仓库的上级品牌分组",
    "general_customer_brands": "一般客户的上级品牌或分类",
    "general_customer_shops": "一般客户下的店铺层级",
    "general_customer_units": "一般客户店铺下的单位层级",
    "general_customer_sort_preferences": "各账户独立的一般客户排序偏好",
    "inventory_account_subjects": "进销存科目字典",
    "purchase_order_requirement_templates": "各品牌生产采购单的要求文本模板",
    "scheduled_task_statuses": "定时任务每个业务日期的执行状态和重试信息",
    "scheduled_task_runs": "定时任务每一次实际运行的开始、完成、耗时和失败信息",
    "dewu_orders": "千百度、伊伴、烟斗、笑脸得物订单统一明细；每日全量覆盖",
    "v_jst_aftersale_returns_normalized": "聚水潭售后退货退款标准化视图",
    "v_jst_monthly_orders_normalized": "聚水潭月订单商品明细标准化视图",
    "v_jst_product_price_normalized": "聚水潭物价资料标准化视图；不再作为库存来源",
    "data_governance_runs": "数据治理任务运行记录",
    "data_quality_issues": "数据质量问题及处理状态",
}


COMMON_FIELD_DESCRIPTIONS = {
    "id": "数据库行主键，不等同于货号或业务单号",
    "source_workbook": "来源 Excel 工作簿名称或路径，用于追溯",
    "source_sheet": "来源工作表名称，用于追溯",
    "source_row_number": "来源工作表行号，用于追溯和去重",
    "raw_payload": "来源原始行 JSON，仅用于追溯，不作为常规统计字段",
    "extra_fields": "未结构化的扩展字段 JSON，使用前需确认具体键名",
    "created_at": "数据库记录创建时间，不等同于业务日期",
    "updated_at": "数据库记录最后修改时间，不等同于业务日期",
    "deleted_at": "逻辑删除时间；为空表示有效记录",
    "brand": "品牌标识或来源品牌值；事实表筛选时优先使用系统内部品牌编码",
    "product_code": "商品编码；销售和库存来源中通常包含基础货号后的颜色或尺码后缀",
    "style_code": "款式编码或款号，具体粒度以来源表为准",
    "product_name": "商品品名",
    "color": "颜色名称",
    "size": "尺码名称",
    "barcode": "商品条码",
    "source_date": "来源文件中的日期文本",
    "source_date_value": "规范化后的来源日期",
    "business_date": "规范化业务日期，优先用于日期筛选",
    "date_value": "由原日期文本解析出的规范日期",
    "sort_order": "展示排序号，数值越小通常越靠前",
}


PRODUCT_ARCHIVE_FIELD_DESCRIPTIONS = {
    "image_path": "商品图片路径；仅用于页面展示，不参与统计",
    "sku": "商品档案当前基础货号，商品档案查询的主业务编码",
    "original_sku": "原始货号或款号，用于款号归并",
    "group_name": "商品组别",
    "cost": "商品档案当前成本；经营单据除批发销售单外应优先与此口径一致",
    "factory_sku": "工厂货号",
    "season_category": "季节分类，例如春夏、春秋、秋冬、冬季；不是春季款标签",
    "year": "年份季节展示标签，例如26年春季款；不是纯数字 2026",
    "upper_material": "鞋面材质",
    "lining_material": "鞋里材质",
    "outsole_material": "外底材质",
    "insole_material": "内底或鞋垫材质",
    "execution_standard": "执行标准",
    "heel_height": "跟高；千百度女鞋中展示为后跟高",
    "sole_style": "跟底款式",
    "fashion_elements": "流行元素",
    "shoe_width": "鞋宽",
    "shoe_length": "鞋长",
    "shaft_circumference": "靴筒围",
    "shaft_height": "靴筒高",
    "internal_height_increase": "内增高高度",
    "internal_height_note": "内增高说明",
    "upper_height": "帮面高度；千百度女鞋中展示为鞋帮高度",
    "opening_depth": "开口深度",
    "boot_shaft": "靴筒",
    "toe_shape": "鞋头形状",
    "closure_type": "闭合方式",
    "mesh_upper_type": "鞋网面类型",
    "shoe_box_spec": "鞋盒规格",
    "first_order_time": "首单时间原始文本",
    "size_range": "商品尺码段或尺码组名称",
    "product_model": "产品型号",
    "supplier_name": "主供应商名称",
    "color_code": "颜色代码；不是完整商品条码",
    "launch_date": "上市日期原始文本",
    "product_level": "商品等级",
    "shoe_box_type": "鞋盒类型",
    "selling_points": "商品卖点",
    "barcode_build_rule": "商品编码构成规则，例如货号+颜色代码+尺码或货号+尺码",
    "product_name": "品名；与产品型号 product_model 区分",
    "last_imported_at": "最近一次导入或回填时间",
    "category": "商品档案分类",
}


FIELD_DESCRIPTIONS = {
    **{
        table_name: PRODUCT_ARCHIVE_FIELD_DESCRIPTIONS
        for table_name in PRODUCT_ARCHIVE_TABLES
    },
    "color_barcodes": {
        "brand": "品牌内部编码",
        "color_barcode": "颜色代码",
        "color_name": "颜色名称",
    },
    "gj_merged_product_info": {
        "row_no": "来源文件内业务序号",
        "goods_code": "管家婆当前货号",
        "original_goods_code": "管家婆原始货号或款号",
        "goods_full_name": "管家婆商品全名",
        "factory_code": "工厂货号或厂家编码",
        "barcode_format": "条码格式说明",
        "launch_date": "上市日期原始文本",
        "insole_material": "内底或鞋垫材质",
        "outsole_material": "外底材质",
        "lining_material": "鞋里材质",
        "upper_material": "鞋面材质",
        "shoe_box_spec": "鞋盒规格",
        "disabled_flag": "管家婆停用标记，可用于判断商品是否有效",
        "primary_supplier": "管家婆主供应商",
        "fine_table_brand": "系统标准品牌内部编码",
    },
    "product_code_mappings": {
        "brand": "品牌内部编码",
        "code_type": "来源编码类型",
        "code_value": "待映射的来源编码",
        "canonical_product_code": "系统标准基础货号",
        "source_system": "编码来源系统",
        "is_active": "是否为当前有效映射",
    },
    "v_product_code_mappings": {
        "brand": "品牌内部编码",
        "code_type": "来源编码类型",
        "code_value": "待映射的来源编码",
        "canonical_product_code": "系统标准基础货号",
        "source_system": "编码来源系统",
    },
    "product_size_group_mappings": {
        "product_code": "商品基础货号",
        "size_group_name": "该商品指定的尺码组名称",
    },
    "size_groups": {
        "name": "尺码组名称",
    },
    "size_group_items": {
        "size_group_id": "所属尺码组 id，关联 size_groups.id",
        "size_name": "尺码显示值，可能是单码或合码",
        "barcode": "该尺码对应的条码片段",
    },
    "v_jst_daily_sales": {
        "sales_date": "销售业务日期",
        "channel": "聚水潭店铺或渠道原始名称；需通过店铺映射归类平台",
        "product_code": "带颜色或尺码后缀的商品编码；匹配档案货号时使用最长前缀命中",
        "style_code": "来源款式编码",
        "color_spec": "颜色及规格原文，常用于解析颜色和尺码",
        "channel_code": "来源渠道代码",
        "order_type": "订单类型",
        "supplier": "来源供应商名称",
        "supplier_style_code": "供应商款号",
        "product_category": "来源商品分类",
        "brand": "聚水潭来源品牌文本，不等同于系统内部品牌编码",
        "cost_price": "来源成本价",
        "shipped_order_count": "发货订单数",
        "sales_order_count": "销售订单数",
        "return_order_count": "退货订单数",
        "sales_quantity": "毛销量，未扣退货",
        "shipped_quantity": "发货数量",
        "return_quantity": "退货数量",
        "net_sales_quantity": "净销量，等于销售数量扣除退货数量；默认销量口径",
        "sales_amount": "毛销售金额",
        "net_sales_amount": "净销售金额",
        "cost_amount": "销售成本金额",
        "gross_profit": "毛利金额",
    },
    "v_vip_daily_sales": {
        "sales_date": "唯品销售业务日期",
        "size_id": "唯品尺码 id",
        "goods_id": "唯品商品 id",
        "goods_code": "唯品商品编码；匹配基础货号时使用前缀",
        "style_code": "唯品款式编码",
        "spu_id": "唯品 SPU id",
        "size_name": "唯品尺码名称",
        "product_image": "唯品商品图片地址",
        "product_type": "唯品商品类型",
        "brand_sn": "唯品品牌编号",
        "brand_name": "唯品品牌名称",
        "sales_amount": "唯品销售金额",
        "sales_quantity": "唯品销量，唯品日销的标准数量字段",
        "customer_count": "购买客户数",
        "on_sale_stock": "唯品在售库存，仅表示唯品来源库存，不替代聚水潭总库存",
        "product_link": "唯品商品链接",
    },
    "v_product_goods_historical_sales": {
        "brand": "系统内部品牌编码",
        "sales_year": "自然销售年份数字",
        "sales_date": "销售日期",
        "channel": "历史店铺或渠道名称",
        "style_code": "款式编码",
        "product_code": "历史商品编码，可能包含尺码后缀",
        "original_sku": "历史原始货号或基础款号",
        "size": "历史销售尺码",
        "sales_quantity": "历史销量",
        "sales_amount": "历史销售金额",
    },
    "product_goods_sales_periods": {
        "brand": "系统内部品牌编码",
        "product_code": "基础货号",
        "style_code": "款式编码",
        "period_type": "统计周期类型，例如 year 或 month",
        "period_start": "统计周期起始日期",
        "sales_quantity": "该周期预计算销量",
        "source_as_of_date": "计算该指标时的数据截至日期",
    },
    "product_goods_shop_channel_mappings": {
        "brand": "系统内部品牌编码",
        "shop_name": "来源店铺名称，对应聚水潭日销 channel",
        "channel": "归类后的平台或赛道，例如天猫、得物、直播赛道、达播清仓",
    },
    "v_product_goods_historical_orders": {
        "brand": "系统内部品牌编码",
        "order_date": "订单业务日期",
        "original_sku": "来源订单商品编码；关联档案时按 sku 最长前缀命中",
        "channel": "订单渠道",
        "order_quantity": "订单数量；不能用销量代替",
    },
    "jst_full_stock": {
        "sync_date": "库存同步日期；当前库存必须限定 MAX(sync_date)",
        "image_url": "来源商品图片地址",
        "style_code": "来源款式编码",
        "product_code": "带颜色或尺码后缀的库存商品编码；匹配档案货号时使用最长前缀",
        "color_spec": "颜色规格原文",
        "product_tag": "聚水潭商品标签",
        "brand": "聚水潭库存源文件中的品牌名称",
        "actual_stock_qty": "实际库存数；在仓库存组成之一",
        "order_occupy_qty": "订单占用库存",
        "available_qty": "可用库存；小于 0 时其绝对值为缺货库存",
        "stock_sale_days": "库存销售天数或周转天数",
        "purchase_feature": "采购特征",
        "suggested_purchase_qty": "系统建议采购数量",
        "purchase_in_transit_qty": "采购在途数量",
        "safety_stock_min_qty": "安全库存下限",
        "safety_stock_max_qty": "安全库存上限",
        "safety_stock_delivery_days_min": "安全库存最小交付天数",
        "safety_stock_days_max": "安全库存最大天数",
        "warehouse_pending_qty": "仓库待处理数量",
        "return_warehouse_stock_qty": "退货仓库存",
        "purchase_warehouse_stock_qty": "进货仓库存；在仓库存组成之一",
        "exception_warehouse_qty": "异常仓库存",
        "off_shelf_warehouse_qty": "下架仓库存",
        "worn_warehouse_qty": "残次或穿着仓库存",
        "live_warehouse_qty": "直播仓库存",
        "off_shelf_inventory_qty": "下架库存数量",
        "processing_warehouse_qty": "加工仓库存",
        "temporary_location_qty": "临时库位库存",
        "transfer_in_transit_qty": "调拨在途数量",
        "return_in_transit_qty": "销退在途数量",
        "inventory_sync_status": "库存同步状态",
        "main_warehouse_location": "主仓库库位",
        "yesterday_sales_qty": "库存源文件提供的昨日销量",
        "sales_7d_qty": "库存源文件提供的近 7 天销量",
        "sales_15d_qty": "库存源文件提供的近 15 天销量",
        "yesterday_return_qty": "库存源文件提供的昨日退货量",
        "return_7d_qty": "库存源文件提供的近 7 天退货量",
        "return_15d_qty": "库存源文件提供的近 15 天退货量",
        "inventory_updated_at": "来源库存更新时间文本",
        "warehouse_name": "来源仓库名称",
    },
    "jst_size_stock": {
        "product_code": "商品编码",
        "size": "尺码",
        "stock_qty": "该商品编码和尺码的当前在仓库存",
    },
    "jst_stock_summary": {
        "stock_date": "来源库存日期文本",
        "stock_date_value": "规范库存日期",
        "product_code": "商品编码",
        "defect_stock_qty": "次品库存",
        "purchase_in_transit_qty": "采购在途汇总数量",
        "off_shelf_qty": "下架数量",
        "order_occupy_qty": "订单占用数量",
    },
    "jst_size_stock_snapshots": {
        "snapshot_date": "尺码库存快照日期",
        "product_code": "商品编码",
        "size": "尺码",
        "stock_qty": "该快照日的尺码库存",
    },
    "jst_stock_summary_snapshots": {
        "snapshot_date": "库存汇总快照日期",
        "product_code": "商品编码",
        "defect_stock_qty": "快照日次品库存",
        "purchase_in_transit_qty": "快照日采购在途",
        "off_shelf_qty": "快照日下架数量",
        "order_occupy_qty": "快照日订单占用数量",
    },
    "v_jst_daily_stock_normalized": {
        "stock_date": "来源库存日期文本",
        "product_code": "商品编码",
        "available_qty": "当日可用库存",
        "stock_date_value": "规范库存日期",
        "business_date": "规范业务日期，等同于可用的库存日期",
    },
    "v_product_goods_detail_snapshots": {
        "brand": "系统内部品牌编码",
        "snapshot_date": "货品表快照日期",
        "goods_code": "快照中的商品货号",
        "style_code": "快照中的款式编码",
        "data": "货品表该行的完整历史指标 JSON；查询具体指标需使用确认过的 JSON 键",
    },
    "v_fine_table_snapshot_rows": {
        "brand": "系统内部品牌编码",
        "snapshot_date": "精细表快照日期",
        "batch_id": "快照批次 id",
        "sku": "快照商品货号",
        "original_sku": "快照原始货号或款号",
        "row_index": "该行在快照中的顺序",
        "payload": "精细表历史行指标 JSON；空值不能自行补 0",
    },
    "v_vip_product_daily_normalized": {
        "goods_id": "唯品商品 id",
        "date": "来源报告日期文本",
        "goods_name": "唯品商品名称",
        "goods_code": "唯品商品编码",
        "style_code": "唯品款式编码",
        "p_spu_id": "唯品父 SPU id",
        "goods_image": "唯品商品图片",
        "brand_sn": "唯品品牌编号",
        "brand_name": "唯品品牌名称",
        "category_l3": "唯品三级分类",
        "first_listing_time": "唯品首次上架时间",
        "main_style": "是否主推款或主款标记",
        "detail_uv": "商品详情 UV",
        "ctr": "点击率原始文本，通常含百分号",
        "fav_count": "收藏数",
        "sales_amount": "报告周期销售金额",
        "sales_volume": "报告周期销量",
        "customer_count": "报告周期客户数",
        "purchase_conversion": "购买转化率原始文本",
        "reject_count": "拒退件数",
        "reject_rate": "拒退率原始文本，通常含百分号",
        "report_type": "报告类型；查询唯品指标必须明确",
        "period": "报告周期；查询唯品指标必须明确",
        "date_range": "来源报告显示的日期范围文本",
        "report_start_date": "报告周期开始日期",
        "report_end_date": "报告周期结束日期",
        "report_start_date_value": "规范化报告开始日期",
    },
    "product_goods_overrides": {
        "brand": "系统内部品牌编码",
        "product_id": "对应品牌商品档案表的 id",
        "platform": "人工维护的所属平台",
        "category_l4": "人工维护的四级分类",
        "product_role": "人工维护的商品角色，例如新品",
        "product_type": "人工维护的商品类型",
        "douyin_hot": "人工填写的抖音爆款文本",
        "clearance": "人工填写的清仓文本",
        "remark": "货品表人工备注",
        "extra_fields": "补单明细、补单后库存和周转等人工字段 JSON",
    },
    "inventory_records": {
        "date": "单据日期原始文本",
        "supplier": "供货单位；批发销售单表示收货客户，同价调拨单表示出货仓库",
        "total_count": "单据头总数量",
        "amount": "单据头总金额",
        "warehouse": "收货仓库；同价调拨单表示入货仓库",
        "document_type": "单据类型，例如进货订单、进货单、报溢单、批发销售单",
        "summary": "单据摘要；追加匹配需结合日期、仓库和单据类型",
        "date_value": "规范单据业务日期",
        "handler": "经手人",
        "document_number": "业务单据编号",
        "additional_note": "附加说明",
    },
    "v_inventory_records_normalized": {
        "date": "单据日期原始文本",
        "supplier": "供货单位；销售类单据表示收货客户，调拨单表示出货仓库",
        "total_count": "单据头总数量",
        "amount": "单据头总金额",
        "warehouse": "收货或入货仓库",
        "document_type": "单据类型",
        "summary": "单据摘要",
        "date_value": "解析后的单据日期",
        "handler": "经手人",
        "document_number": "业务单据编号",
        "additional_note": "附加说明",
        "business_date": "规范业务日期，优先用于筛选和排序",
    },
    "ai_purchase_records": {
        "date": "采购单日期原始文本",
        "supplier": "采购供应商",
        "total_count": "采购单总数量",
        "amount": "采购单总金额",
        "warehouse": "采购单收货仓库",
        "document_type": "固定为进货订单",
        "summary": "采购单摘要",
        "date_value": "规范采购单日期",
        "handler": "经手人",
        "document_number": "采购单编号",
        "additional_note": "附加说明",
    },
    "inventory_details": {
        "document_id": "所属单据 id，关联 inventory_records.id",
        "product_code": "单据商品货号，不应使用商品条码代替",
        "quantity": "明细数量",
        "unit_price": "明细单价",
        "amount": "明细金额，通常为数量乘单价",
        "product_name": "商品名称",
        "color_spec": "颜色规格原文",
        "color_barcode": "颜色代码",
        "color_name": "颜色名称",
        "size_quantities": "各尺码数量 JSON，展示时转为尺码: 数量",
        "remark": "明细备注",
    },
    "ai_purchase_details": {
        "document_id": "所属采购单 id，关联 ai_purchase_records.id",
        "product_code": "采购商品货号",
        "quantity": "采购明细数量",
        "unit_price": "采购明细单价",
        "amount": "采购明细金额",
        "product_name": "商品名称",
        "color_spec": "颜色规格原文",
        "color_barcode": "颜色代码",
        "color_name": "颜色名称",
        "size_quantities": "各尺码采购数量 JSON",
        "remark": "明细备注",
    },
    "suppliers": {
        "name": "供应商名称",
        "contact": "联系人或联系电话",
        "address": "供应商地址",
        "notes": "供应商备注",
        "factory_code": "工厂代码",
        "brand": "所属品牌内部编码或品牌名称",
        "wechat": "微信联系方式",
        "cooperation_status": "合作状态",
        "factory_grade": "历史工厂等级字段；等级业务逻辑已停用，不应用于当前评级",
        "factory_suggestion": "工厂建议",
    },
    "supplier_brands": {
        "code": "品牌内部编码，例如 cbanner_mens、eblan、ni、ns",
        "name": "品牌中文展示名称",
        "product_archive_enabled": "该品牌是否启用商品档案",
        "product_table_name": "该品牌绑定的商品档案表名",
    },
    "warehouses": {
        "name": "仓库名称",
        "address": "仓库地址",
        "notes": "仓库备注",
        "brand": "仓库所属品牌或分组名称",
    },
    "warehouse_brands": {
        "name": "仓库品牌分组名称",
    },
    "general_customer_brands": {
        "name": "一般客户上级品牌名称",
        "category_name": "一般客户分类名称",
    },
    "general_customer_shops": {
        "customer_name": "上级一般客户名称",
        "shop_name": "店铺名称",
    },
    "general_customer_units": {
        "shop_id": "所属店铺 id，关联 general_customer_shops.id",
        "unit_name": "店铺下的单位名称",
    },
    "general_customer_sort_preferences": {
        "user_id": "排序偏好所属账户 id",
        "scope": "排序层级范围",
        "parent_id": "上级对象 id",
        "item_id": "被排序对象 id",
    },
    "inventory_account_subjects": {
        "code": "科目代码",
        "category": "科目分类，收入类或支出类",
        "name": "科目名称",
    },
    "purchase_order_requirement_templates": {
        "brand": "品牌内部编码",
        "content": "生产采购单要求文本",
    },
    "scheduled_task_statuses": {
        "task_name": "定时任务名称",
        "business_date": "任务对应的业务日期",
        "status": "任务状态，例如 running、success、failed",
        "source_path": "任务读取的数据源路径",
        "message": "执行结果或失败原因摘要",
        "result": "任务返回的结构化结果 JSON",
        "attempts": "该业务日期累计执行次数",
        "first_started_at": "首次开始时间",
        "last_started_at": "最近一次开始时间",
        "finished_at": "最近一次结束时间",
    },
    "scheduled_task_runs": {
        "task_name": "Windows 定时任务名称",
        "status": "本次运行状态：running、success 或 failed",
        "started_at": "本次运行开始时间",
        "finished_at": "本次运行完成时间",
        "duration_ms": "本次运行耗时，单位毫秒",
        "exit_code": "进程退出码，0 表示成功",
        "host_name": "执行任务的服务器名称",
        "process_id": "外层任务运行器进程号",
        "command": "实际执行的业务命令",
        "log_path": "对应文件日志路径",
        "error_summary": "失败时截取的末尾错误摘要",
    },
    "dewu_orders": {
        "brand_group": "内部品牌编码：cbanner、eblan、yandou、smiley",
        "brand_label": "品牌中文名称",
        "order_date": "由买家下单时间解析出的订单日期",
        "order_number": "得物订单号；同一订单可能因商品明细出现多行",
        "spu_id": "得物 SPU ID",
        "sku_id": "得物 SKU ID",
        "goods_code": "商品基础货号",
        "sku_goods_code": "源文件中的 SKU 货号",
        "specification": "规格，通常包含颜色和尺码",
        "quantity": "订单商品数量",
        "bid_amount": "出价金额（元）",
        "seller_discount_amount": "卖家承担优惠金额（元）",
        "consumer_postage_subsidy_amount": "消费者邮费补贴金额（元）",
        "estimated_income_amount": "预计收入金额（元）",
        "order_status": "当前得物订单状态",
        "buyer_order_time": "买家下单时间原始文本",
        "buyer_payment_time": "买家支付时间原始文本",
        "seller_shipping_time": "卖家发货时间原始文本",
        "order_closed_time": "订单关闭时间原始文本",
        "source_modified_at": "来源 Excel 文件最后修改时间",
    },
    "v_jst_aftersale_returns_normalized": {
        "original_goods_code": "售后原始商品编码",
        "returned_qty": "退货退款数量",
        "order_date": "订单日期原始文本",
        "order_date_value": "规范订单日期",
        "order_time": "订单时间原始文本",
        "platform_site": "平台站点",
        "shop_name": "店铺名称",
        "online_order_id": "线上订单号",
        "order_time_value": "规范订单日期",
        "business_date": "规范业务日期",
    },
    "v_jst_monthly_orders_normalized": {
        "internal_order_id": "聚水潭内部订单号",
        "online_order_id": "平台线上订单号",
        "buyer_account": "买家账号",
        "platform_site": "平台站点",
        "order_time": "下单时间原始文本",
        "ship_date": "发货日期原始文本",
        "shop_name": "店铺名称",
        "payable_amount": "应付金额",
        "paid_amount": "实付金额",
        "status": "订单状态",
        "address": "收货地址",
        "order_type": "订单类型",
        "shop_style_code": "店铺款式编码",
        "quantity": "商品数量",
        "category": "来源商品分类",
        "registered_qty": "登记数量",
        "actual_return_qty": "实际退货数量",
        "cost_price": "来源成本价",
        "shop_status": "店铺订单状态",
        "buyer_paid": "买家支付金额",
        "seller_received": "卖家实收金额",
        "online_sub_order_id": "线上子订单号",
        "order_time_at": "规范下单时间",
        "ship_date_value": "规范发货日期",
        "order_time_value": "规范下单时间",
    },
    "v_jst_product_price_normalized": {
        "goods_code": "商品货号",
        "goods_full_name": "商品全名",
        "latest_purchase_price": "最新进货价",
        "cost_unit_price": "成本单价",
        "member_price": "会员价",
        "retail_price": "零售价",
        "preset_price_name": "预设售价名称",
        "preset_price": "预设售价；当前商品档案成本回填采用的价格口径",
        "preset_discount_name": "预设折扣名称",
        "preset_discount": "预设折扣",
        "preset_commission_name": "预设提成名称",
        "preset_commission": "预设提成",
        "business_date": "规范物价资料日期",
    },
}


def table_description(table_name: str) -> str | None:
    normalized = table_name.lower()
    if normalized.startswith("manual_product_archive_"):
        return "手工品牌商品档案；一行代表一个商品货号，字段结构与标准商品档案相近"
    return TABLE_DESCRIPTIONS.get(normalized)


def field_description(table_name: str, field_name: str) -> str | None:
    normalized_table = table_name.lower()
    normalized_field = field_name.lower()
    table_fields = FIELD_DESCRIPTIONS.get(normalized_table)
    if table_fields and normalized_field in table_fields:
        return table_fields[normalized_field]
    if normalized_table.startswith("manual_product_archive_"):
        archive_description = PRODUCT_ARCHIVE_FIELD_DESCRIPTIONS.get(normalized_field)
        if archive_description:
            return archive_description
    return COMMON_FIELD_DESCRIPTIONS.get(normalized_field)
