from __future__ import annotations

from sqlalchemy import BigInteger, Column, Date, DateTime, Identity, Index, Integer, JSON, Numeric, Table, Text, func

from domain.schema import METADATA


DEWU_ORDERS_TABLE = Table(
    "dewu_orders",
    METADATA,
    Column("id", BigInteger, Identity(always=False), primary_key=True),
    Column("brand_group", Text, nullable=False),
    Column("brand_label", Text, nullable=False),
    Column("source_workbook", Text, nullable=False),
    Column("source_sheet", Text, nullable=False),
    Column("source_row_number", Integer, nullable=False),
    Column("source_modified_at", DateTime(timezone=True), nullable=True),
    Column("order_date", Date, nullable=True),
    Column("order_number", Text, nullable=False),
    Column("order_type", Text, nullable=True),
    Column("spu_id", Text, nullable=True),
    Column("sku_id", Text, nullable=True),
    Column("product_name", Text, nullable=True),
    Column("goods_code", Text, nullable=True),
    Column("sku_goods_code", Text, nullable=True),
    Column("brand_name", Text, nullable=True),
    Column("specification", Text, nullable=True),
    Column("quantity", Integer, nullable=True),
    Column("bid_amount", Numeric(18, 2), nullable=True),
    Column("seller_discount_amount", Numeric(18, 2), nullable=True),
    Column("consumer_postage_subsidy_amount", Numeric(18, 2), nullable=True),
    Column("estimated_income_amount", Numeric(18, 2), nullable=True),
    Column("remaining_shipping_time", Text, nullable=True),
    Column("close_reason", Text, nullable=True),
    Column("delivery_party", Text, nullable=True),
    Column("logistics_company", Text, nullable=True),
    Column("logistics_tracking_number", Text, nullable=True),
    Column("appointment_number", Text, nullable=True),
    Column("order_status", Text, nullable=True),
    Column("order_source", Text, nullable=True),
    Column("dewu_receiving_address", Text, nullable=True),
    Column("recipient_name", Text, nullable=True),
    Column("recipient_phone", Text, nullable=True),
    Column("recipient_province", Text, nullable=True),
    Column("recipient_city", Text, nullable=True),
    Column("recipient_district", Text, nullable=True),
    Column("recipient_street", Text, nullable=True),
    Column("recipient_detail_address", Text, nullable=True),
    Column("service_guarantee", Text, nullable=True),
    Column("direct_shipping_pickup_time", Text, nullable=True),
    Column("direct_shipping_warehouse", Text, nullable=True),
    Column("user_identifier", Text, nullable=True),
    Column("order_remark", Text, nullable=True),
    Column("order_tag", Text, nullable=True),
    Column("buyer_order_time", Text, nullable=True),
    Column("buyer_payment_time", Text, nullable=True),
    Column("promised_delivery_time", Text, nullable=True),
    Column("seller_shipping_time", Text, nullable=True),
    Column("platform_receiving_time", Text, nullable=True),
    Column("platform_shipping_time", Text, nullable=True),
    Column("order_closed_time", Text, nullable=True),
    Column("intent_deposit_amount", Numeric(18, 2), nullable=True),
    Column("full_payment_amount", Numeric(18, 2), nullable=True),
    Column("sub_waybill_number", Text, nullable=True),
    Column("third_party_order_number", Text, nullable=True),
    Column("onsite_ticket_address", Text, nullable=True),
    Column("has_engraving_remark", Text, nullable=True),
    Column("buyer_remark", Text, nullable=True),
    Column("custom_product_detail", Text, nullable=True),
    Column("preorder_number", Text, nullable=True),
    Column("appointment_store", Text, nullable=True),
    Column("verification_store", Text, nullable=True),
    Column("verification_time", Text, nullable=True),
    Column("order_identifier", Text, nullable=True),
    Column("pickup_carrier", Text, nullable=True),
    Column("pickup_waybill_number", Text, nullable=True),
    Column("pickup_code", Text, nullable=True),
    Column("sn_code", Text, nullable=True),
    Column("imei1", Text, nullable=True),
    Column("imei2", Text, nullable=True),
    Column("reservation_open_time", Text, nullable=True),
    Column("extra_fields", JSON, nullable=True),
    Column("created_at", DateTime(timezone=True), server_default=func.date_trunc("minute", func.now())),
    Column(
        "updated_at",
        DateTime(timezone=True),
        server_default=func.date_trunc("minute", func.now()),
        onupdate=func.date_trunc("minute", func.now()),
    ),
)

Index("idx_dewu_orders_brand_order_date", DEWU_ORDERS_TABLE.c.brand_group, DEWU_ORDERS_TABLE.c.order_date)
Index("idx_dewu_orders_order_number", DEWU_ORDERS_TABLE.c.order_number)
Index(
    "idx_dewu_orders_goods_code",
    DEWU_ORDERS_TABLE.c.goods_code,
    postgresql_ops={"goods_code": "text_pattern_ops"},
)
Index("idx_dewu_orders_sku_id", DEWU_ORDERS_TABLE.c.sku_id)
Index("idx_dewu_orders_order_status", DEWU_ORDERS_TABLE.c.order_status)
